version: '3.4'
services:
  gm-app:
    image: gm-api:latest
    ports:
      - '5000:5000'
    expose:
      - '5000'
  classifier-app:
   image: pedia-classifier-api:latest
   ports:
     - '9000:9000'
   expose:
      - '9000'
  middleware-app:
    image: middleware-app:latest
    ports:
      - '7000:7000'
    expose:
      - '7000'
    networks:
      - varfish
networks:
  varfish:
